version: '3.8'

networks:
  robot_network:
    external: true


volumes:
    ros-bin: 
    boost-lib:
    python-packages:

services:
  ros-core:
    build: ./roscore
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=ros-core
       - ROS_MASTER_URI=http://ros-core:11311
    ports:
      - "11311:11311"
    volumes:
      - ros-bin:/opt/ros/noetic
      - boost-lib:/usr/include/boost
    networks:
      - robot_network

  ros-board:
    depends_on:
      - ros-core
    image: dragomirxyz/rosboard
    environment: 
       - ROS_HOSTNAME=ros-board
       - ROS_MASTER_URI=http://ros-core:11311
    ports:
      - "8888:8888"
    volumes:
      - ros-bin:/opt/ros/noetic
    networks:
      - robot_network

  motor-board:
    depends_on:
      - ros-core
    privileged: true
    build: ./rosserial
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=motor-board
       - ROS_MASTER_URI=http://ros-core:11311
       - SERIAL_PORT=/dev/ttyACM0
    volumes:
      - ros-bin:/opt/ros/noetic
      - boost-lib:/usr/include/boost
      - /home/cdr/Robotics:/app/data:rw
    devices:
      - "/dev:/dev"
    networks:
      - robot_network

  imu:
    depends_on:
      - ros-core
    privileged: true  
    build: ./imu
    environment: 
       - ROS_HOSTNAME=imu
       - ROS_MASTER_URI=http://ros-core:11311
    volumes:
      - ros-bin:/opt/ros/noetic
      - boost-lib:/usr/include/boost
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    networks:
      - robot_network

  ros-lidar:
    depends_on:
      - ros-core
    privileged: true
    build: ./roslidar
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=ros-lidar
       - ROS_MASTER_URI=http://ros-core:11311
    volumes:
      - ros-bin:/opt/ros/noetic
      - boost-lib:/usr/include/boost
    devices:
      - "/dev:/dev"
    networks:
      - robot_network

  ros-joystick:
    depends_on:
      - ros-core
    privileged: true
    build: ./rosxbox
    environment: 
       - ROS_HOSTNAME=ros-joystick
       - ROS_MASTER_URI=http://ros-core:11311
    volumes:
      - ros-bin:/opt/ros/noetic
      - boost-lib:/usr/include/boost
    devices:
      - "/dev:/dev"
    networks:
      - robot_network